baseURL = 'https://mingfei.io/'
languageCode = 'en-us'
title = "Mingfei's Blog"

theme = "nostyleplease"

[services]
  [services.googleAnalytics]
    ID = 'G-D7MFC9EKLE'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true